Add support for oracle functions and object storage
lithops-cloud/lithops pull request #1103
Opened 2023-05-18 08:29 UTC by abourramouss

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

This pull request adds support for the oracle backend using lithops.

2023-05-18 12:06 UTC, JosepSampe requested changes
Thanks for the contribution @abourramouss. 

Please, add only files related to oracle and remove all the modifications in all the rest

2023-05-18 12:07 UTC, JosepSampe commented on .github/workflows/python-app.yml
Please remove this workflow

2023-05-18 12:10 UTC, JosepSampe requested changes
Thanks for the contribution @abourramouss.

Please, add only files related to oracle and remove all the modifications in all the rest

2023-05-18 12:10 UTC, JosepSampe commented on Dockerfile
Why is this file located in the root of lithops? Please remove this file

2023-05-18 12:10 UTC, JosepSampe commented on examples/call_async.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/call_async_class.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/call_async_java.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/ibmcos_arg.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/call_async_cython.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/function.cpython-39-x86_64-linux-gnu.so
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/multicloud.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/rabbitmq_arg.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on examples/wait.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on lithops/serverless/backends/aliyun_fc/aliyun_fc.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on lithops/serverless/backends/aws_lambda/aws_lambda.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on lithops/serverless/backends/azure_functions/entry_point.py
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on runtime/aws_lambda/Dockerfile
Please remove the changes on this file from this PR

2023-05-18 12:10 UTC, JosepSampe commented on setup.py
> +    'oci'
Please remove this line

2023-05-24 12:12 UTC, JosepSampe requested changes
Can you add the copyright header to all the .py files (except \__init__.py files)?

2023-05-24 12:12 UTC, JosepSampe commented on lithops/storage/backends/oracle_oss/config.py
> +# (C) Copyright Cloudlab URV 2020
Should be 2023?

2023-05-25 11:59 UTC, JosepSampe commented on docs/source/compute_config/oracle_functions.md
> +    runtime_memory: <RUNTIME_MEMORY>
You can remove max_workers, runtime and runtime_memory from here if they are not mandatory

2023-05-25 11:59 UTC, JosepSampe commented on docs/source/storage_config/oracle_oss.md
> +    storage_bucket : <STORAGE_BUCKET>
is `storege_bucket` needed here?

2023-05-25 11:59 UTC, JosepSampe commented on lithops/serverless/backends/oracle_f/oracle_f.py
> +        raise Exception("Function %s not found.", runtime_name)
Add a blank line at the end of the file

2023-05-25 11:59 UTC, JosepSampe commented on lithops/serverless/backends/oracle_f/config.py
> +    config_data['oracle_f'].update(config_data['oracle'])
Add a blank line at the end of the file

2023-09-05 08:12 UTC, JosepSampe commented on lithops/serverless/backends/oracle_f/config.py
> +}
Is Oracle functions available only for python3.8? I can see you added a Dockefile, so: does this mean Oracle Functions can work with any Python version?

2023-09-11 10:40 UTC, merged

2023-09-11 12:36 UTC, abourramouss commented on lithops/serverless/backends/oracle_f/config.py
> +}
It actually depends on the oci-sdk, it must run on any version the oci-sdk supports.
The oci-sdk supports Python 3.6, 3.7, 3.8 and 3.9.